import { useState } from 'react';
import { ArrowDownToLine, ArrowLeft, ArrowRight, Copy, Swords } from 'lucide-react';
import { download } from '../content';
import { copyText, Toggle } from '../ui';
const size=(n:number)=>n>1048576?(n/1048576).toFixed(1)+' MB':Math.max(1,Math.round(n/1024))+' KB';
export function Downloads({path,navigate,fight,assistance,setAssistance,busy=false,worldAvailable=true,encounterConfigured=true}:{path:string;navigate:(url:string)=>void;fight:()=>void;assistance:boolean;setAssistance:(v:boolean)=>void;busy?:boolean;worldAvailable?:boolean;encounterConfigured?:boolean}) {
 const [copied,setCopied]=useState('');const available=download.status==='available'&&download.bytes>0&&/^[a-f0-9]{64}$/i.test(download.sha256);
 const route=new URL(path,location.origin);const segments=route.pathname.split('/').filter(Boolean);const detail=segments.length===2;const badId=segments.length>2||(segments[1]&&segments[1]!==download.productId);const expected:Record<string,string>={release:download.releaseId,artifact:download.artifactId,version:download.version,os:'all',arch:'all'};const badSelection=Object.entries(expected).some(([key,value])=>route.searchParams.has(key)&&(route.searchParams.getAll(key).length!==1||route.searchParams.get(key)!==value));if(badId||badSelection)return <><p>{badId?'Download not found.':'This file selection is not available.'}</p><button onClick={()=>navigate('/downloads')}>Back to downloads</button></>;
 return detail?<div className="download-detail"><button className="text-button" onClick={()=>navigate('/downloads')}><ArrowLeft size={15}/>Downloads</button><div className="file-symbol" aria-hidden="true"><span/><span/><span/></div><h2>{download.title}</h2><p>{download.summary}</p><dl className="file-meta"><div><dt>Version</dt><dd>{download.version}</dd></div><div><dt>File</dt><dd>{download.format}</dd></div><div><dt>Size</dt><dd>{available?size(download.bytes):'Unavailable'}</dd></div><div><dt>Platform</dt><dd>Any</dd></div></dl><p className="filename">{download.filename}</p><div className="action-row"><button className={encounterConfigured?'primary':'secondary'} disabled={!available||busy||!worldAvailable||!encounterConfigured} aria-describedby={(!worldAvailable||!encounterConfigured)?'fight-unavailable':undefined} onClick={fight}><Swords size={17}/>Fight & download</button><a className={'button '+(encounterConfigured?'secondary ':'primary ')+(!available?'disabled':'')} aria-disabled={!available} href={available?download.url:undefined} download={download.filename}><ArrowDownToLine size={16}/>Download file</a></div>{(!worldAvailable||!encounterConfigured)&&<p id="fight-unavailable">{!encounterConfigured?'The encounter is not ready.':'The world must be ready to fight.'} You can download the file directly.</p>}{!available&&<p>File is unavailable.</p>}{encounterConfigured&&<Toggle label="Combat assistance" description="Slower attacks. No player damage." value={assistance} onChange={setAssistance}/>}<details className="checksum"><summary>SHA-256</summary><code>{download.sha256||'Unavailable'}</code><button className="text-button" disabled={!available} onClick={()=>copyText(download.sha256).then(()=>setCopied('Checksum copied')).catch(()=>setCopied('Select the checksum to copy it.'))}><Copy size={14}/>Copy checksum</button><span role="status">{copied}</span></details><a href={download.documentationUrl} onClick={e=>{e.preventDefault();navigate(download.documentationUrl)}}>Read documentation <ArrowRight size={14}/></a></div>:<><a href={'/downloads/'+download.productId} className="file-row" onClick={e=>{e.preventDefault();navigate('/downloads/'+download.productId)}}><div className="file-symbol small" aria-hidden="true"><span/><span/><span/></div><div><h2>{download.title}</h2><p>{download.summary}</p><small>{download.format} · {download.version}{available?' · '+size(download.bytes):' · Unavailable'}</small></div><ArrowRight size={19}/></a></>
}

