// Dumps the stand-in's code-authored motion for the packager: every pose key that the clips name (the lab's
// player.clips.json + the World's sit clip), resolved to its Pose and solved to a 2D skeleton (hip, knees,
// ankles, shoulders, elbows, hands, weapon). The Blender-side mapper drives the Rosace rig from these, so the
// timing/pose order stays identical to the clip definitions. Read-only over src/; writes data/standin_solved.json.
//   node tools/rosace-package/standin_dump.mjs
// The type-strip hooks are the ones src/world/tools/character-assets-regressions.mjs uses (attribution: same repo).
import { readFileSync, writeFileSync } from "node:fs";
import { registerHooks, stripTypeScriptTypes } from "node:module";
import { fileURLToPath } from "node:url";
import path from "node:path";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const REPO = path.resolve(HERE, "../..");
registerHooks({ load(url, context, next) {
  const u = new URL(url);
  if (u.search === "?raw") return { format: "module", shortCircuit: true, source: `export default ${JSON.stringify(readFileSync(u, "utf8"))}` };
  if (u.protocol === "file:" && u.pathname.endsWith(".ts")) {
    return { format: "module", shortCircuit: true, source: stripTypeScriptTypes(readFileSync(u, "utf8"), { mode: "transform", sourceUrl: url }) };
  }
  return next(url, context);
} });

const { solve } = await import(`${REPO}/src/lab/art/standin-figure.ts`.replace(/^([A-Za-z]):/, "file:///$1:"));
const { blendPoses, resolvePose, POSES } = await import(`${REPO}/src/lab/art/standin-poses.ts`.replace(/^([A-Za-z]):/, "file:///$1:"));
const { WORLD_CLIPS } = await import(`${REPO}/src/world/player/standin.ts`.replace(/^([A-Za-z]):/, "file:///$1:"));

// The World's seated poses (src/world/player/standin.ts keeps them private; copied here verbatim).
const sit0 = { hip: [-4, -30], lean: -3, chest: 6, head: 8, footN: [16, -3], footF: [20, -3], toeN: -6, toeF: -4,
  wpn: [13, -50, -87], slide: 50, handN: [9, -30], hair: 4, cloth: 34, clothLift: 0.1, expr: "open" };
const WORLD = { sit0, sit1: { ...sit0, hip: [-4, -29.6], chest: 7, head: 9, wpn: [13, -49.6, -87], handN: [9, -29.6], hair: 2, cloth: 33 } };
const poseFor = (key) => {
  const m = /^(\w+)~(\w+):([\d.]+)$/.exec(key);
  if (m && (WORLD[m[1]] || WORLD[m[2]])) return blendPoses(poseFor(m[1]), poseFor(m[2]), Number(m[3]));
  return WORLD[key] ?? resolvePose(key);
};

const lab = JSON.parse(readFileSync(`${REPO}/src/lab/data/player.clips.json`, "utf8"));
const clips = [...lab.clips, ...WORLD_CLIPS];
const keys = new Map();
for (const c of clips) for (const f of c.frames) {
  const pose = poseFor(f.pose);
  const sk = solve(pose);
  keys.set(f.pose, { pose, sk });
}
const out = {
  note: "generated by tools/rosace-package/standin_dump.mjs from src/lab/art/standin-poses.ts (+ the World sit poses); figure space: x forward, y down, origin = ground between the feet, 96 px character",
  clips: clips.map((c) => ({ id: c.id, loop: !!c.loop, next: c.next ?? null, frames: c.frames.map((f) => ({ pose: f.pose, duration: f.duration, hold: f.hold ?? 0, phase: f.phase ?? null })) })),
  poses: Object.fromEntries([...keys].map(([k, v]) => [k, v])),
};
writeFileSync(path.join(HERE, "data", "standin_solved.json"), JSON.stringify(out, null, 1));
console.log("clips", clips.length, "frames", clips.reduce((n, c) => n + c.frames.length, 0), "unique pose keys", keys.size);
