// The engine lane's recipes: the proof props, the sandbox room pieces and
// the shared kit (docs/props/ENGINE.md, "Kit"). Import them directly from
// here when you need one by name.
//
// Region lanes do NOT edit this file: put a recipe in
// src/pixel/props/<region>/<name>.ts and it is registered automatically
// (src/pixel/registry.ts finds every exported recipe by its id). Hosts look
// recipes up there: findRecipe("map-banner").

// proof props and room pieces
export { floor } from "./floor.ts";
export { wall } from "./wall.ts";
export { gauge } from "./gauge.ts";
export { candelabra } from "./candelabra.ts";
export { donationBox, donorPlaque } from "./donation.ts";
export { stainedGlass } from "./stainedGlass.ts";
export { mapBanner } from "./mapBanner.ts";
export { bossTerminal } from "./bossTerminal.ts";
export { font } from "./font.ts";

// the shared kit
export { shrineLantern, offeringBowl } from "./shrine.ts";
export { door, type DoorKind } from "./door.ts";
export { lampPost } from "./lampPost.ts";
export { bench } from "./bench.ts";
export { candles } from "./candles.ts";
export { hangingLantern } from "./hangingLantern.ts";
export { hangingBell } from "./bell.ts";
export { clothHanging } from "./cloth.ts";
export { prayerFlags } from "./flags.ts";
export { grass, vines } from "./plants.ts";
export { crate, barrel, rubble } from "./crates.ts";
export { luggage } from "./luggage.ts";
export { sign } from "./sign.ts";
export { cable } from "./cable.ts";
export { pillar } from "./pillar.ts";
export { trainingDummy } from "./dummy.ts";
export { lever } from "./lever.ts";
export { dust, moths, puddle, paper } from "./ambient.ts";
