import {useEffect,useState} from 'react';
import {SocialController} from './controller';
import type {SocialPeer} from './types';

export function SocialPanel({controller,onClose,onVoice}:{controller:SocialController;onClose?:()=>void;onVoice?:()=>void}){
  const [state,setState]=useState(controller.snapshot()),[selected,setSelected]=useState<SocialPeer|null>(null),[notice,setNotice]=useState(''),[confirmBlock,setConfirmBlock]=useState(false),[busy,setBusy]=useState(false);
  useEffect(()=>controller.subscribe(setState),[controller]);
  const present=selected?state.peers.find(peer=>peer.accountId===selected.accountId):null;
  const person=present||selected;
  async function action(task:()=>Promise<void>){if(busy)return;setBusy(true);setNotice('');try{await task();}catch(error){setNotice((error as Error).message);}finally{setBusy(false);}}
  return <aside className="nearby-panel" aria-labelledby="nearby-title"><header><h2 id="nearby-title">Nearby</h2>{onClose&&<button data-control="SOC-009" onClick={onClose}>Close nearby</button>}</header><label><input data-control="SOC-002" type="checkbox" checked={state.enabled} onChange={e=>void action(()=>controller.setEnabled(e.target.checked))}/>Show nearby visitors</label><p className="social-status" role="status">{notice||state.message|| (state.enabled?'Your world stays independent.':'Nearby is off.')}</p>{state.status==='unavailable'&&<button data-control="SOC-008" disabled={busy} onClick={()=>void action(()=>controller.setEnabled(true))}>Retry nearby</button>}{state.capacity&&<p>Showing the nearest eligible visitors.</p>}{state.peers.length===0&&state.enabled&&<p>No nearby visitors are visible here.</p>}<ul>{state.peers.map(peer=><li key={peer.id}><button data-control="SOC-003" onClick={()=>{setSelected(peer);setConfirmBlock(false);}}>{peer.alias}{peer.speaking?' · speaking':''}{peer.muted?' · muted':''}</button></li>)}</ul>
    {person&&<section className="person-controls" aria-label={`Controls for ${person.alias}`}><h3>{person.alias}</h3>{!present&&<p>This person has left your visible audience.</p>}<button data-control="SOC-004" disabled={busy} onClick={()=>void action(()=>controller.personAction(person.muted?'unmute':'mute',person.accountId))}>{person.muted?'Unmute person':'Mute person'}</button><button data-control="SOC-005" onClick={()=>setConfirmBlock(true)}>Block person</button>{confirmBlock&&<div><p>Block {person.alias}? You will stop seeing and hearing each other.</p><button disabled={busy} onClick={()=>void action(async()=>{await controller.personAction('block',person.accountId);setConfirmBlock(false);setNotice('Person blocked.');})}>Confirm block</button><button onClick={()=>setConfirmBlock(false)}>Cancel</button></div>}<form onSubmit={e=>{e.preventDefault();const reason=String(new FormData(e.currentTarget).get('reason'));void action(async()=>{await controller.report(person.accountId,reason);setNotice('Report sent to the site owner. No audio was recorded.');});}}><label>Reason<select name="reason"><option>Harassment</option><option>Disruptive audio</option><option>Impersonation</option><option>Other inappropriate behavior</option></select></label><button data-control="SOC-007" disabled={busy}>Report person</button></form></section>}
    {state.blocked.length>0&&<section><h3>Blocked people</h3>{state.blocked.map(person=><p key={person.id}>{person.alias} <button data-control="SOC-006" disabled={busy} onClick={()=>void action(()=>controller.personAction('unblock',person.id))}>Unblock</button></p>)}</section>}
    {onVoice&&<button onClick={onVoice}>Voice</button>}
  </aside>;
}
