import {useEffect,useState} from 'react';
import {VoiceController} from './voice';

export function VoicePanel({controller,onClose}:{controller:VoiceController;onClose?:()=>void}){
  const [state,setState]=useState(controller.snapshot());useEffect(()=>controller.subscribe(setState),[controller]);
  const joined=!['off','joining','error'].includes(state.state);
  return <aside className="voice-panel" aria-labelledby="voice-title"><header><h2 id="voice-title">Voice</h2>{onClose&&<button onClick={()=>{controller.release();onClose();}}>Close voice controls</button>}</header><p role="status" aria-live="polite">{state.message||'Voice is off.'}</p><p>Hold V in the world or hold Talk. Release stops capture. No recording.</p>{state.state==='off'||state.state==='error'?<button data-control="VOI-001" onClick={()=>void controller.join()}>Join voice</button>:<button data-control="VOI-002" onClick={()=>void controller.leave()}>{state.state==='joining'?'Cancel connection':'Leave voice'}</button>}
    {joined&&<><button data-control="VOI-003" disabled={state.state==='permission'||state.state==='talking'} onClick={()=>void controller.enableMicrophone()}>Enable microphone</button><button data-control="VOI-004" className="talk-hold" aria-pressed={state.state==='talking'} disabled={state.state==='permission'} onPointerDown={e=>{e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);void controller.press(true);}} onPointerUp={()=>controller.release()} onPointerCancel={()=>controller.release()} onLostPointerCapture={()=>controller.release()} onKeyDown={e=>{if((e.code==='Space'||e.code==='Enter')&&!e.repeat){e.preventDefault();void controller.press(true);}}} onKeyUp={e=>{if(e.code==='Space'||e.code==='Enter'){e.preventDefault();controller.release();}}}>Hold to talk</button>{state.devices.length>0&&<label>Microphone<select data-control="VOI-005" value={state.deviceId} onChange={e=>controller.setDevice(e.target.value)}><option value="">System microphone</option>{state.devices.map((device,index)=><option key={device.deviceId} value={device.deviceId}>{device.label||`Microphone ${index+1}`}</option>)}</select></label>}</>}
    <label>Voice volume<input data-control="VOI-006" type="range" min="0" max="100" value={Math.round(state.volume*100)} onChange={e=>controller.setVolume(Number(e.target.value)/100)}/><output>{Math.round(state.volume*100)}%</output></label><button data-control="VOI-007" aria-pressed={state.muted} onClick={()=>controller.setMuted(!state.muted)}>{state.muted?'Unmute voices':'Mute all voices'}</button>{state.state==='permission'&&<button data-control="VOI-009" onClick={()=>controller.release()}>Cancel microphone setup</button>}
  </aside>;
}
