import {lazy,Suspense,useCallback,useEffect,useRef,useState,type CSSProperties} from 'react';
import {createRoot} from 'react-dom/client';
import '@fontsource/inter/400.css';
import '@fontsource/inter/500.css';
import {getWorldAudio,audioRegionFor} from './audio';
import type {Command,GameEvent,GameHandle,InputAction,Panel,RoomId,Settings} from './contracts';
import {readProgress,readSettings,saveProgress,SETTINGS_KEY} from './progress';
import {ROOMS} from './rooms';
import {PanelBoundary} from './PanelBoundary';
import './registry.css';

const keys:Record<string,InputAction>={a:'left',arrowleft:'left',d:'right',arrowright:'right',' ':'jump',shift:'dash',j:'slash',e:'interact'};
const GamePanel=lazy(()=>import('./panels').then(module=>({default:module.GamePanel})));
function App(){
 const host=useRef<HTMLDivElement>(null),game=useRef<GameHandle|null>(null),audio=useRef(getWorldAudio()),[settings,setSettings]=useState<Settings>(readSettings),[progress,setProgress]=useState(readProgress),[panel,setPanel]=useState<Panel|null>(null),[ready,setReady]=useState(false),[entered,setEntered]=useState(false),[active,setActive]=useState(false),[error,setError]=useState(''),[loading,setLoading]=useState<{room:RoomId;loaded:number;total:number}|null>(null),[room,setRoom]=useState<RoomId>('arrival'),[black,setBlack]=useState(false),[attempt,setAttempt]=useState(0),[audioError,setAudioError]=useState(''),[saveError,setSaveError]=useState(false),[coarse,setCoarse]=useState(matchMedia('(pointer:coarse)').matches),[hud,setHud]=useState<Extract<GameEvent,{type:'hud'}>>({type:'hud',health:3,maximum:3});
 const state=useRef({active,ready,entered,panel,settings,progress,room});state.current={active,ready,entered,panel,settings,progress,room};const sink=useRef<(e:GameEvent)=>void>(()=>{});const panelStack=useRef<Panel[]>([]);const physicalInput=useRef(new Set<InputAction>());
 const sendInput=useCallback((action:InputAction,down:boolean)=>{if(down)physicalInput.current.add(action);else physicalInput.current.delete(action);game.current?.command({type:'input',action,down})},[]);
 const pause=useCallback(()=>{state.current.active=false;physicalInput.current.clear();game.current?.command({type:'active',value:false});setActive(false)},[]);
 const focus=()=>{state.current.active=true;game.current?.command({type:'active',value:true});setActive(true);host.current?.focus({preventScroll:true})};
 const enableAudio=()=>{setAudioError('');const s=state.current;audio.current.setScene({region:audioRegionFor(s.room==='exhibit'?'gallery':s.room==='vestibule'?'dispatch':s.room),content:s.panel?.kind==='art'?'art':s.panel?.kind==='docs'?'reader':s.panel?'panel':'none',paused:!s.active});void audio.current.enableFromGesture().catch(()=>setAudioError('Sound could not start. Try the sound control again.'))};
 const enter=()=>{if(!ready||loading||error)return;setEntered(true);focus();if(settings.sound)enableAudio();else audio.current.mute()};
 const close=()=>{if(panelStack.current.length){setPanel(panelStack.current.pop()!);return}setPanel(null);game.current?.command({type:'close'});if(state.current.entered){focus();requestAnimationFrame(()=>host.current?.focus({preventScroll:true}));if(state.current.settings.sound)void audio.current.resumeFromGesture().catch(()=>setAudioError('Sound could not resume.'))}};
 const open=(next:Panel)=>{panelStack.current=[];pause();setPanel(next)};
 const navigatePanel=(next:Panel)=>{const current=state.current.panel;if(panelStack.current.at(-1)?.kind===next.kind){setPanel(panelStack.current.pop()!);return}if(current&&current.kind!==next.kind)panelStack.current.push(current);setPanel(next)};
 const command=(c:Command)=>{if(c.type==='restart')panelStack.current=[];if(c.type==='input')sendInput(c.action,c.down);else game.current?.command(c)};
 sink.current=e=>{switch(e.type){case'ready':setReady(true);setLoading(null);setError('');game.current?.command({type:'settings',settings:state.current.settings});break;case'load':setLoading({room:e.room,loaded:e.loaded,total:e.total});setError('');break;case'error':setError(e.message);setLoading(null);pause();break;case'room':setRoom(e.room);setLoading(null);setError('');if(state.current.active)for(const action of physicalInput.current)if(action==='left'||action==='right')sendInput(action,true);break;case'panel':open(e.panel);break;case'progress':setProgress(e.progress);setSaveError(!saveProgress(e.progress));break;case'hud':setHud(e);break;case'black':setBlack(e.value);break;case'effect':if(state.current.settings.sound&&state.current.active)audio.current.playEffect(e.id,e.eventId);break;}};
 useEffect(()=>{let cancelled=false;setReady(false);setError('');setLoading({room:progress.checkpoint,loaded:0,total:0});void import('./index').then(({createRegistry})=>createRegistry(host.current!,e=>{if(!cancelled)sink.current(e)},state.current.progress)).then(handle=>{if(cancelled){handle.destroy();return}game.current=handle;handle.command({type:'settings',settings:state.current.settings})}).catch(e=>{if(!cancelled){setError(e instanceof Error?e.message:'The game could not load.');setLoading(null)}});return()=>{cancelled=true;game.current?.destroy();game.current=null}},[attempt]);
 useEffect(()=>{game.current?.command({type:'settings',settings});audio.current.setGains({master:settings.master,music:settings.music,effects:settings.effects,ambience:.4});try{localStorage.setItem(SETTINGS_KEY,JSON.stringify(settings))}catch{}},[settings]);
 useEffect(()=>{audio.current.setScene({region:audioRegionFor(room==='exhibit'?'gallery':room==='vestibule'?'dispatch':room),content:panel?.kind==='art'?'art':panel?.kind==='docs'?'reader':panel?'panel':'none',paused:!active});},[room,panel,active]);
 useEffect(()=>{const diagnostics=Object.freeze({snapshot:()=>audio.current.diagnostics()});Object.defineProperty(window,'__registryAudio',{configurable:true,value:diagnostics});return()=>{delete (window as unknown as Record<string,unknown>).__registryAudio;audio.current.dispose()}},[]);
 useEffect(()=>{const changed=()=>{const d=audio.current.diagnostics();if(d.lastError)setAudioError('Sound could not load. Try the sound control again.')};window.addEventListener('world-audio-status',changed);return()=>window.removeEventListener('world-audio-status',changed)},[]);
 useEffect(()=>{const down=(e:KeyboardEvent)=>{const s=state.current,target=e.target as HTMLElement;if(target.closest('input,textarea,select,[contenteditable]'))return;if(e.key==='Escape'&&s.active){e.preventDefault();pause();setPanel({kind:'pause'});return}if(!s.active||s.panel||target.closest('button,a'))return;if(e.key==='Tab'){pause();return}const action=keys[e.key.toLowerCase()];if(action){e.preventDefault();sendInput(action,true)}};const up=(e:KeyboardEvent)=>{const action=keys[e.key.toLowerCase()];if(action)sendInput(action,false)};const release=()=>sendInput('slash',false);const blur=()=>{pause();audio.current.pause()};const visibility=()=>{if(document.hidden)blur()};const media=matchMedia('(pointer:coarse)'),pointer=()=>setCoarse(media.matches);window.addEventListener('keydown',down);window.addEventListener('keyup',up);window.addEventListener('pointerup',release);window.addEventListener('pointercancel',release);window.addEventListener('blur',blur);window.addEventListener('orientationchange',blur);document.addEventListener('visibilitychange',visibility);media.addEventListener('change',pointer);return()=>{window.removeEventListener('keydown',down);window.removeEventListener('keyup',up);window.removeEventListener('pointerup',release);window.removeEventListener('pointercancel',release);window.removeEventListener('blur',blur);window.removeEventListener('orientationchange',blur);document.removeEventListener('visibilitychange',visibility);media.removeEventListener('change',pointer)}},[pause]);
 const touch=(action:InputAction,label:string,text:string)=><button aria-label={label} disabled={!active||!!panel} onPointerDown={e=>{e.preventDefault();e.stopPropagation();e.currentTarget.setPointerCapture(e.pointerId);command({type:'input',action,down:true})}} onPointerUp={()=>command({type:'input',action,down:false})} onPointerCancel={()=>command({type:'input',action,down:false})} onLostPointerCapture={()=>command({type:'input',action,down:false})}>{text}</button>;
 const retry=()=>{setError('');if(game.current){game.current.command({type:'retry'});if(entered)focus()}else setAttempt(n=>n+1)};
 return <div className={'registry-app '+(settings.reduced?'reduced ':'')+(settings.touchSize==='large'?'large-touch':'')} style={{'--registry-letterbox':String(hud.letterbox||0)+'px'} as CSSProperties}>
  <div ref={host} className={'registry-canvas '+(ready?'is-ready':'')} tabIndex={0} role="region" aria-label="The Registry. A and D move. Space double jumps. Shift dashes. Click or J attacks. E interacts. Tab leaves gameplay." onPointerDown={e=>{if(e.button!==0)return;if(!state.current.active){if(entered&&!panel)enter();return}e.preventDefault();host.current?.focus({preventScroll:true});command({type:'pointer',x:e.clientX-e.currentTarget.getBoundingClientRect().left,y:e.clientY-e.currentTarget.getBoundingClientRect().top})}}/>
  <div className="registry-bar top" aria-hidden="true"/><div className="registry-bar bottom" aria-hidden="true"/>
  <header className="registry-hud"><span className="registry-brand" aria-label="dex">dex</span><div><button aria-label={settings.sound?'Turn sound off':'Turn sound on'} onClick={()=>{const value=!settings.sound;setSettings({...settings,sound:value});if(value&&entered)enableAudio();else audio.current.mute()}}>{settings.sound?'♪':'♩'}</button><button aria-label="Pause menu" onClick={()=>open({kind:'pause'})}>☰</button></div></header>
  {!entered&&!error&&<div className="registry-entry"><span className="registry-entry-brand" aria-hidden="true">dex</span><button className="registry-enter" disabled={!ready||!!loading} onClick={enter}>{ready&&!loading?'Enter':'Loading'}</button><button className="registry-sound-choice" aria-pressed={settings.sound} onClick={()=>setSettings({...settings,sound:!settings.sound})}>Sound {settings.sound?'on':'off'}</button></div>}
  {entered&&!active&&!panel&&!loading&&!error&&!black&&<button className="registry-resume" onClick={enter}>Resume</button>}
  {loading&&<div className="registry-loading" role="status"><span>{entered?ROOMS[loading.room].name:'Loading room'}</span>{loading.total>0&&<progress value={loading.loaded} max={loading.total} aria-label="Room materials"/>}{ready&&entered&&<button onClick={()=>{command({type:'cancel-passage'});focus()}}>Stay here</button>}</div>}
  {error&&<div className="registry-failure" role="alert"><p>{error}</p><button onClick={retry}>Retry</button>{ready&&entered&&<button onClick={()=>{command({type:'cancel-passage'});focus()}}>Stay here</button>}{game.current&&<button onClick={()=>{pause();setAttempt(n=>n+1)}}>Reload game</button>}</div>}
  {entered&&active&&hud.prompt&&!black&&<div className="registry-prompt" style={{left:Math.max(70,Math.min(innerWidth-70,hud.prompt.x)),top:Math.max(80,Math.min(innerHeight-160,hud.prompt.y))}}><kbd>{hud.prompt.action}</kbd><span>{hud.prompt.label}</span></div>}
  {entered&&hud.health<hud.maximum&&!panel&&<div className="registry-health" aria-label={`Health ${hud.health} of ${hud.maximum}`}>{Array.from({length:hud.maximum},(_,i)=><i key={i} className={i<hud.health?'full':''}/>)}</div>}
  {hud.boss&&hud.boss.phase!=='gone'&&<div className="registry-boss"><span>Dispatch seal</span><progress value={hud.boss.health} max={hud.boss.maximum} aria-label="Warden health"/></div>}
  {coarse&&entered&&!panel&&<div className="registry-touch"><div>{touch('left','Move left','←')}{touch('right','Move right','→')}</div><div>{touch('interact','Interact','E')}{touch('dash','Dash','»')}{touch('slash','Attack','╱')}{touch('jump','Jump; press again for double jump','↑')}</div></div>}
  {(audioError||saveError)&&<div className="registry-notice" role="status">{audioError||'Progress could not be saved in this browser.'}</div>}
  {panel&&<PanelBoundary close={()=>{panelStack.current=[];close()}}><Suspense fallback={<div className="registry-loading" role="status">Loading record…</div>}><GamePanel panel={panel} progress={progress} settings={settings} setSettings={setSettings} setPanel={navigatePanel} command={command} close={close} inEncounter={room==='arena'}/></Suspense></PanelBoundary>}
  <div className={'registry-black '+(black?'shown':'')} aria-hidden="true"/>
 </div>;
}
createRoot(document.getElementById('registry-root')!).render(<App/>);
