import {lazy,Suspense,useEffect,useRef,useState,type ReactNode} from 'react';
import downloadContent from './download-content.json';
const {download,releases:documentationReleases}=downloadContent;
const DocsPanel=lazy(()=>import('./DocumentPanel'));
import {illustrations} from './art';
import {Donate} from '../sections/Donate';
import {ROOMS} from './rooms';
import type {Command,Panel,Progress,Settings} from './contracts';

export function Modal({title,children,close,wide=false,dialogue=false}:{title:string;children:ReactNode;close:()=>void;wide?:boolean;dialogue?:boolean}){
 const ref=useRef<HTMLDivElement>(null);const closeRef=useRef(close);closeRef.current=close;
 useEffect(()=>{const previous=document.activeElement as HTMLElement;requestAnimationFrame(()=>ref.current?.querySelector<HTMLElement>('[data-initial-focus]')?.focus());const key=(e:KeyboardEvent)=>{if(e.key==='Escape'){e.preventDefault();e.stopPropagation();closeRef.current();return}if(e.key!=='Tab')return;const items=Array.from(ref.current?.querySelectorAll<HTMLElement>('button:not(:disabled),a[href],input,select,textarea,[tabindex="0"]')||[]).filter(x=>x.getClientRects().length>0);if(!items.length){e.preventDefault();return}const first=items[0],last=items[items.length-1];if(e.shiftKey&&(document.activeElement===first||!ref.current?.contains(document.activeElement))){e.preventDefault();last.focus()}else if(!e.shiftKey&&(document.activeElement===last||!ref.current?.contains(document.activeElement))){e.preventDefault();first.focus()}};document.addEventListener('keydown',key,true);return()=>{document.removeEventListener('keydown',key,true);if(previous?.isConnected)previous.focus({preventScroll:true})}},[]);
 return <div className={dialogue?'registry-dialogue-layer':'registry-shade'} onPointerDown={e=>{if(e.target===e.currentTarget)close()}}><div ref={ref} className={'registry-panel '+(wide?'wide ':'')+(dialogue?'registry-dialogue-bubble':'')} role="dialog" aria-modal="true" aria-labelledby="registry-panel-title"><header><h1 id="registry-panel-title" tabIndex={-1} data-initial-focus>{title}</h1><button className="registry-icon" aria-label={'Close '+title} onClick={close}>×</button></header><div className="registry-panel-body">{children}</div></div></div>;
}

const placements:Record<string,[number,number]>={arrival:[200,240],rest:[55,240],registry:[355,240],junction:[505,240],vestibule:[660,240],arena:[820,240],archive:[430,350],'low-passage':[505,120],pool:[355,120],'sky-walk':[200,120],exhibit:[200,30],courtyard:[355,30]};
const edges=[['rest','arrival'],['arrival','registry'],['registry','junction'],['junction','vestibule'],['vestibule','arena'],['junction','archive'],['archive','registry'],['junction','low-passage'],['low-passage','pool'],['pool','sky-walk'],['sky-walk','exhibit'],['exhibit','courtyard']];
function MapPanel({progress}:{progress:Progress}){return <><div className="registry-map"><svg viewBox="0 -15 895 420" role="img" aria-label="Registry floor plan. Receiving hall connects to an overlook and registry. The junction branches toward dispatch, archive, and the upper exhibit route.">{edges.map(([a,b])=><path key={a+b} d={`M${placements[a][0]} ${placements[a][1]}L${placements[b][0]} ${placements[b][1]}`} stroke="currentColor" fill="none" opacity=".35"/>)}<path d="M355 30V240" stroke="currentColor" fill="none" strokeDasharray={progress.courtyard?undefined:'5 8'} opacity={progress.courtyard?.65:.2}/>{Object.entries(placements).map(([id,[x,y]])=><g key={id} transform={`translate(${x} ${y})`}><rect x="-5" y="-5" width="10" height="10" fill="currentColor" opacity={progress.rooms.includes(id as never)?1:.4}/><text y="25" textAnchor="middle" fill="#e5dcc5">{ROOMS[id as keyof typeof ROOMS].name}</text></g>)}</svg></div><p className="registry-note">{progress.courtyard?'The courtyard passage is connected.':'The courtyard passage is disconnected.'}</p></>}

function ArtPanel({id,onSelect,onViewed}:{id:string;onSelect:(id:string)=>void;onViewed:(id:string)=>void}){
 const index=illustrations.findIndex(a=>a.id===id),art=illustrations[index],frame=useRef<HTMLDivElement>(null),[zoom,setZoom]=useState(1),[loaded,setLoaded]=useState(false),[failed,setFailed]=useState(false);
 useEffect(()=>{setZoom(1);setLoaded(false);setFailed(false)},[id]);
 if(!art)return <p>Illustration unavailable.</p>;
 return <><div className="registry-art-tools"><span>{index+1} / {illustrations.length}</span><div><button disabled={zoom<=1} aria-label="Zoom out" onClick={()=>setZoom(z=>Math.max(1,z-.5))}>−</button><button onClick={()=>setZoom(1)}>Fit</button><button disabled={zoom>=3} aria-label="Zoom in" onClick={()=>setZoom(z=>Math.min(3,z+.5))}>+</button></div></div><div ref={frame} className="registry-art-view" aria-busy={!loaded&&!failed}>{failed?<p>Image could not load. <button onClick={()=>{setFailed(false);setLoaded(false)}}>Retry</button></p>:<img key={id} src={art.src} width={art.width} height={art.height} alt={art.alt} style={zoom>1?{maxWidth:'none',maxHeight:'none',width:`${zoom*100}%`,height:'auto'}:undefined} onLoad={()=>{setLoaded(true);onViewed(id)}} onError={()=>setFailed(true)}/>}</div><nav className="registry-art-nav" aria-label="Artwork"><button disabled={index===0} onClick={()=>onSelect(illustrations[index-1].id)}>← Previous</button><span>{art.title}</span><button disabled={index===illustrations.length-1} onClick={()=>onSelect(illustrations[index+1].id)}>Next →</button></nav></>;
}

function ProductPanel(){const [version,setVersion]=useState(download.version),[status,setStatus]=useState('');const chosen=documentationReleases.find(d=>d.version===version)||download;const valid=chosen.status==='available'&&chosen.bytes>0&&/^[a-f\d]{64}$/i.test(chosen.sha256);return <><p className="registry-note">dex.place</p><h2>{chosen.title}</h2><label className="registry-field">Edition<select value={version} onChange={e=>{setVersion(e.target.value);setStatus('')}}>{documentationReleases.map(d=><option key={d.version} value={d.version}>{d.version}</option>)}</select></label><dl className="registry-facts"><div><dt>Format</dt><dd>{chosen.format}</dd></div><div><dt>Size</dt><dd>{(chosen.bytes/1024).toFixed(0)} KB</dd></div></dl><a className="registry-primary" href={valid?chosen.url:undefined} download={chosen.filename} aria-disabled={!valid} onClick={e=>{if(!valid)e.preventDefault();else setStatus('Download requested.')}}>Download</a><details><summary>File details</summary><p>{chosen.filename}</p><code className="registry-checksum">{chosen.sha256}</code></details><p role="status" className="registry-note">{status}</p></>}

export function GamePanel({panel,progress,settings,setSettings,setPanel,command,close,inEncounter=false}:{panel:Panel;progress:Progress;settings:Settings;setSettings:(s:Settings)=>void;setPanel:(p:Panel)=>void;command:(c:Command)=>void;close:()=>void;inEncounter?:boolean}){
 const titles:Record<Panel['kind'],string>={pause:'Pause',controls:'Controls',settings:'Settings',reset:'Start again',map:'Map',accountant:'Accountant','sky-door':'Courtyard',rest:'Overlook',latch:'Courtyard latch',donate:'Donate',donors:'Top donors',consignment:'Dispatch',product:'Collection',catalogue:'Illustrations',art:illustrations.find(a=>a.id===panel.id)?.title||'Illustration',docs:'Records'};
 const act=(c:Command)=>{command(c);close()};
 return <Modal title={titles[panel.kind]} close={close} wide={['map','catalogue','art','docs'].includes(panel.kind)} dialogue={panel.kind==='accountant'}>
  {panel.kind==='pause'&&<div className="registry-menu"><button onClick={close}>Resume</button><button onClick={()=>setPanel({kind:'settings'})}>Settings</button><button onClick={()=>setPanel({kind:'controls'})}>Controls</button>{inEncounter&&<button onClick={()=>act({type:'leave-encounter'})}>Leave arena</button>}<button onClick={()=>setPanel({kind:'reset'})}>Start again</button></div>}
  {panel.kind==='controls'&&<><dl className="registry-controls"><div><dt>A / D · ← / →</dt><dd>Move</dd></div><div><dt>Space</dt><dd>Jump; press again to double jump</dd></div><div><dt>Shift</dt><dd>Dash</dd></div><div><dt>Click / J</dt><dd>Slash</dd></div><div><dt>E</dt><dd>Use / inspect</dd></div><div><dt>Escape</dt><dd>Pause / close</dd></div><div><dt>Tab</dt><dd>Leave gameplay controls</dd></div></dl><p className="registry-note">Touch controls support movement and an action together.</p></>}
  {panel.kind==='settings'&&<div className="registry-settings">{(['master','music','effects'] as const).map(key=><label key={key}><span>{key[0].toUpperCase()+key.slice(1)} <output>{Math.round(settings[key]*100)}%</output></span><input type="range" min="0" max="100" step="5" value={settings[key]*100} onChange={e=>setSettings({...settings,[key]:Number(e.target.value)/100})}/></label>)}<label className="registry-check"><span>Reduced motion</span><input type="checkbox" checked={settings.reduced} onChange={e=>setSettings({...settings,reduced:e.target.checked})}/></label><label className="registry-check"><span>Combat assistance</span><input type="checkbox" checked={settings.assistance} onChange={e=>setSettings({...settings,assistance:e.target.checked})}/></label><p className="registry-note">Assistance extends the warden’s openings and prevents combat damage.</p><label className="registry-field">Touch controls<select value={settings.touchSize} onChange={e=>setSettings({...settings,touchSize:e.target.value as Settings['touchSize']})}><option value="normal">Normal</option><option value="large">Large</option></select></label></div>}
  {panel.kind==='reset'&&<><p>Clear this game’s local exploration and start at the receiving hall?</p><div className="registry-actions"><button onClick={close}>Keep exploring</button><button onClick={()=>act({type:'restart'})}>Start again</button></div></>}
  {panel.kind==='map'&&<MapPanel progress={progress}/>}
  {panel.kind==='accountant'&&<><p className="registry-dialogue">{progress.courtyard?'“You found it.”':'“The courtyard door used to open beside this desk.”'}</p>{!progress.courtyard&&<p className="registry-dialogue">“Red railing. One tree. You can still see it from upstairs.”</p>}<button className="registry-primary" onClick={close}>Continue</button></>}
  {panel.kind==='sky-door'&&<><p className="registry-dialogue">Beyond the landing, only sky.</p><button onClick={close}>Step back</button></>}
  {panel.kind==='rest'&&<><p className="registry-dialogue">Stay a while.</p><button className="registry-primary" onClick={()=>act({type:'rest'})}>Rest</button></>}
  {panel.kind==='latch'&&<><p>The maintenance latch holds the return door shut.</p><button className="registry-primary" onClick={()=>act({type:'latch'})}>Release latch</button></>}
  {panel.kind==='donate'&&<><Donate/><button className="registry-back" onClick={()=>setPanel({kind:'donors'})}>Top donors →</button></>}
  {panel.kind==='donors'&&<><p>Donor records are not connected in this preview.</p><button onClick={()=>setPanel({kind:'donate'})}>Donate</button></>}
  {panel.kind==='consignment'&&<><p className="registry-note">Available collection</p><h2>{download.title}</h2><p>Defeat the dispatch seal to collect the file.</p><div className="registry-actions"><button onClick={close}>Leave</button><button className="registry-primary" onClick={()=>act({type:'challenge'})}>Enter arena</button></div></>}
  {panel.kind==='product'&&<ProductPanel/>}
  {panel.kind==='docs'&&<Suspense fallback={<p role='status'>Loading records…</p>}><DocsPanel/></Suspense>}
  {panel.kind==='catalogue'&&<div className="registry-art-grid">{illustrations.map(a=><button key={a.id} onClick={()=>setPanel({kind:'art',id:a.id})}><img src={a.thumbnailSrc} width={a.thumbnailWidth} height={a.thumbnailHeight} alt=""/><span>{a.title}</span></button>)}</div>}
  {panel.kind==='art'&&<ArtPanel id={panel.id||''} onSelect={id=>setPanel({kind:'art',id})} onViewed={id=>command({type:'mark-art-seen',id})}/>}
 </Modal>;
}
