import type {RoomId} from './contracts';
import {applySceneGeometry} from './scene-geometry';
export interface Surface {id:string;x:number;y:number;width:number;height:number;oneway?:boolean;stair?:boolean;material?:'stone'|'metal'}
export interface Portal {id:string;x:number;y:number;target:RoomId;entry:string;automatic?:'left'|'right';courtyard?:boolean;width?:number;height?:number}
export interface Prop {id:string;kind:'npc'|'rest'|'donate'|'donors'|'map'|'consignment'|'docs'|'catalogue'|'art'|'latch'|'bridge';x:number;y:number;asset:string;width:number;height:number;itemId?:string;interactY?:number;cutPoint?:{x:number;y:number};cordFixed?:{x:number;y:number};aperture?:{x:number;y:number;width:number;height:number}}
export interface Room {id:RoomId;name:string;width:number;height:number;floor:number;referenceLeft:number;camera:{x:number;y:number};entries:Record<string,{x:number;y:number;facing:1|-1}>;portals:Portal[];props:Prop[];solids:Surface[];safe:boolean;music:'calm'|'silent'|'arena';viewOffset:{x:number;y:number};sentry?:{x:number;left:number;right:number};bridge?:{x:number;y:number;length:number;post?:{x:number;y:number};fixed?:{x:number;y:number}};npc?:{x:number;y:number};bossX?:number;descent?:{x:number;y:number};ascent?:{x:number;y:number}}
const at=(x:number,y=740,facing:1|-1=1)=>({x,y,facing});
const door=(id:string,x:number,target:RoomId,entry:string,y=740):Portal=>({id,x,y,target,entry});
const prop=(id:string,kind:Prop['kind'],x:number,asset:string,width:number,height:number,y=740):Prop=>({id,kind,x,y,asset,width,height});
const base=(id:RoomId,name:string):Room=>({id,name,width:1600,height:1000,floor:740,referenceLeft:0,camera:{x:800,y:450},entries:{left:at(130),right:at(1470,740,-1)},portals:[],props:[],solids:[{id:'ground',x:0,y:740,width:1600,height:260}],safe:true,music:'calm',viewOffset:{x:0,y:0}});
const all:Room[]=[];
const arrival=base('arrival','Receiving hall');Object.assign(arrival,{width:2800,floor:718.3,referenceLeft:600,camera:{x:1400,y:450},entries:{home:at(1400,718.3),left:at(130,718.3),right:at(2670,718.3,-1)},solids:[{id:'ground',x:0,y:718.3,width:2800,height:281.7}],portals:[{...door('overlook',55,'rest','right',718.3),automatic:'left'},{...door('registry',2745,'registry','left',718.3),automatic:'right'}]});all.push(arrival);
const rest=base('rest','Overlook');rest.portals=[{...door('hall',1545,'arrival','left'),automatic:'right'}];rest.props=[prop('bench','rest',720,'bench',145,88)];all.push(rest);
const registry=base('registry','Registry');registry.portals=[{...door('hall',55,'arrival','right'),automatic:'left'},{...door('court',1545,'junction','left'),automatic:'right'},{...door('courtyard',1130,'courtyard','return'),courtyard:true},door('archive-return',1340,'archive','return')];registry.props=[prop('accountant','npc',670,'registry-desk',200,105),prop('support','donate',930,'donor-box',46,64),prop('supporters','donors',985,'paper-terminal',38,53)];all.push(registry);
const junction=base('junction','Circulation court');junction.portals=[{...door('registry',55,'registry','right'),automatic:'left'},door('dispatch',1440,'vestibule','left'),door('archive',820,'archive','left'),door('upper',350,'low-passage','right')];junction.props=[prop('map','map',1060,'map-banner',120,165,660)];all.push(junction);
const vestibule=base('vestibule','Dispatch');vestibule.portals=[door('court',140,'junction','right')];vestibule.entries.arena=at(1160,740,-1);vestibule.props=[prop('collection','consignment',1160,'paper-terminal',78,105),prop('support','donate',530,'donor-box',46,64),prop('supporters','donors',588,'paper-terminal',38,53)];all.push(vestibule);
const arena=base('arena','Dispatch seal');arena.safe=false;arena.music='arena';arena.entries.left=at(330);all.push(arena);
const archive=base('archive','Archive');archive.music='silent';archive.entries.return=at(1400,740,-1);archive.portals=[door('court',120,'junction','left'),door('registry',1470,'registry','right')];archive.props=[prop('records','docs',600,'paper-terminal',80,105)];all.push(archive);
const low=base('low-passage','Service passage');low.music='silent';low.safe=false;low.portals=[door('court',1450,'junction','left'),door('reflecting-room',120,'pool','right')];low.solids=[{id:'ground',x:0,y:740,width:1600,height:260},{id:'step1',x:790,y:724,width:230,height:16},{id:'step2',x:830,y:708,width:150,height:16}];low.sentry={x:630,left:420,right:780};all.push(low);
const pool=base('pool','Reflecting room');pool.portals=[door('passage',1480,'low-passage','left'),door('sky',120,'sky-walk','left')];pool.props=[prop('bench','rest',700,'bench',145,88)];all.push(pool);
const sky=base('sky-walk','Sky walk');sky.safe=false;sky.portals=[door('pool',100,'pool','left'),door('exhibit',1470,'exhibit','left')];sky.solids=[{id:'left',x:0,y:740,width:660,height:260},{id:'right',x:1100,y:740,width:500,height:260}];sky.props=[prop('bridge','bridge',620,'bridge-rope',24,145)];sky.viewOffset={x:700,y:-180};all.push(sky);
const exhibit=base('exhibit','Exhibit');exhibit.width=3100;exhibit.camera.x=800;exhibit.solids=[{id:'ground',x:0,y:740,width:3100,height:260}];exhibit.entries.right=at(2960,740,-1);exhibit.portals=[door('sky',100,'sky-walk','right'),door('courtyard',3000,'courtyard','left')];exhibit.props=[prop('catalogue','catalogue',270,'paper-terminal',60,85),prop('support','donate',2810,'donor-box',46,64),prop('supporters','donors',2865,'paper-terminal',38,53)];all.push(exhibit);
const courtyard=base('courtyard','Courtyard');courtyard.entries.return=at(1220,740,-1);courtyard.portals=[door('exhibit',100,'exhibit','right'),{...door('registry',1230,'registry','left'),courtyard:true}];courtyard.props=[prop('latch','latch',1160,'courtyard-latch',35,60),prop('bench','rest',700,'bench',145,88)];courtyard.viewOffset={x:1350,y:-350};all.push(courtyard);
// Each portal returns beside its physical counterpart rather than the room edge.
registry.entries.courtyard=at(1060,740,-1);registry.entries.archive=at(1270,740,-1);
junction.entries.dispatch=at(1360,740,-1);junction.entries.archive=at(750,740,-1);junction.entries.upper=at(420,740,1);
courtyard.portals.find(p=>p.id==='registry')!.entry='courtyard';
archive.portals.find(p=>p.id==='registry')!.entry='archive';archive.portals.find(p=>p.id==='court')!.entry='archive';
vestibule.portals.find(p=>p.id==='court')!.entry='dispatch';low.portals.find(p=>p.id==='court')!.entry='upper';
export const ROOMS=Object.fromEntries(all.map(r=>[r.id,r])) as Record<RoomId,Room>;
applySceneGeometry(ROOMS);
export function roomAssets(room:Room):string[]{return [...new Set([...room.props.map(p=>p.asset),...(room.portals.some(p=>!p.automatic)?['door-frame','door-leaf','door-recess']:[]),...(room.id==='registry'?['accountant-idle','accountant-acknowledge','accountant-rest']:[]),...(room.id==='junction'?['bridge-rope']:[]),...(room.id==='sky-walk'?['bridge','bridge-rope','bridge-post']:[]),...(room.id==='courtyard'?['courtyard-latch-base']:[]),...(room.id==='arena'||room.sentry?['warden-idle','warden-attack','warden-recover','warden-hit','warden-death']:[])])]}
