"""Glaive-hands lane: construct the rose-window stamps for the glaive's disc (DESIGN 7: "gold ring, 8 glass cells (A2
and A3 alternating), 1 px A5 centre") at 144 and 80 px, written as data to art/rosace/hands/glaive/rose_<px>.json.

  python tools/art-construct/gh_rose.py [--sheet OUT.png]

Construction (a pixel artist's rose at 11-13 px, not a downsampled render): a ring of gold, lit on the key-light side
(G1, upper right on screen) and shaded on the other (G3); the four gold spokes carry the cross arms through the
window (the processional cross reads through the disc); each quadrant is split along its diagonal into two cells,
A2 and A3 alternating round the rose (8 cells, no second leading line: at this size a diagonal line of leading
turned the cells to specks); an A5 centre with an A4 halo on the spokes' first pixels; one A4 glint in the lit cell.
Letters: G/H/J = G2/G1/G3 ring, g = G2 spoke, a = A2, b = A3, c = A4, h = A5, O = outline (only painted over the
disc's own outline). author_hands.py rotates the stamp by quarter turns to the haft and paints it over the disc's
rendered pixels when the disc faces the viewer (min_facing).
"""
import argparse
import json
import math
import os

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(HERE))
OUT = os.path.join(REPO, "art", "rosace", "hands", "glaive")
KEY = {"G": "G2", "H": "G1", "J": "G3", "g": "G2", "k": "G1", "a": "A2", "b": "A3", "c": "A4", "h": "A5", "O": "OL"}
LIGHT = (0.63, -0.78)            # the key light on screen (x right, y down), rosace/render.py LIGHT_CAM


def rose(n, ring, glint=True):
    c = (n - 1) / 2.0
    rows = []
    R = n / 2.0
    for y in range(n):
        row = ""
        for x in range(n):
            dx, dy = x - c, y - c
            r = math.hypot(dx, dy)
            if r > R - 0.15:
                row += "."
                continue
            if r > R - ring - 0.35:
                lit = (dx * LIGHT[0] + dy * LIGHT[1]) / max(r, 1e-6)
                row += "H" if lit > 0.45 else ("J" if lit < -0.45 else "G")
                continue
            if dx == 0 and dy == 0:
                row += "h"
                continue
            if abs(dx) < 0.5 or abs(dy) < 0.5:          # spokes: the cross through the window
                row += "c" if r < 1.5 else ("k" if (dx * LIGHT[0] + dy * LIGHT[1]) > 0 else "g")
                continue
            # quadrant split on the diagonal: 8 cells, A2 / A3 alternating round the rose
            q = (0 if dx > 0 else 1) + (0 if dy < 0 else 2)
            half = 1 if abs(dx) > abs(dy) else 0
            idx = {0: 0, 1: 3, 3: 4, 2: 7}[q] + (half if q in (0, 3) else 1 - half)
            row += "a" if idx % 2 == 0 else "b"
        rows.append(row)
    if glint:
        # one A4 glint in the cell nearest the light, one pixel in from the ring
        best = None
        for y, row in enumerate(rows):
            for x, ch in enumerate(row):
                if ch in "ab":
                    dx, dy = x - c, y - c
                    s = dx * LIGHT[0] + dy * LIGHT[1]
                    if best is None or s > best[0]:
                        best = (s, x, y)
        _, x, y = best
        rows[y] = rows[y][:x] + "c" + rows[y][x + 1:]
    return rows


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--sheet", default=None)
    a = ap.parse_args()
    os.makedirs(OUT, exist_ok=True)
    specs = {144: (13, 1, 0.85), 80: (7, 1, 0.85)}
    for px, (n, ring, mf) in specs.items():
        rows = rose(n, ring, glint=px >= 128)
        json.dump({"_doc": f"Rose window of the glaive 'Lancet', {px} px sprite (DESIGN 7). Generated by "
                           "tools/art-construct/gh_rose.py (the construction is in its docstring); placed by "
                           "tools/pixel-pipeline/author_hands.py on the projected disc centre.",
                   "px": px, "rows": rows, "key": KEY, "min_facing": mf,
                   "on": ["gold", "glass", "glass2", "glasscore", "haft"], "over_bg": False},
                  open(os.path.join(OUT, f"rose_{px}.json"), "w"), indent=1)
        print(px)
        print("\n".join(rows))
    if a.sheet:
        import sys
        sys.path.insert(0, os.path.join(REPO, "tools", "pixel-pipeline"))
        from PIL import Image
        import faces
        pal = faces.palette()
        ims = []
        for px in (144, 80):
            R = json.load(open(os.path.join(OUT, f"rose_{px}.json")))
            n = len(R["rows"])
            im = Image.new("RGBA", (n + 4, n + 4), (96, 96, 104, 255))
            for y, row in enumerate(R["rows"]):
                for x, ch in enumerate(row):
                    if ch != ".":
                        im.putpixel((x + 2, y + 2), tuple(pal[KEY[ch]]) + (255,))
            ims.append(im.resize((im.width * 16, im.height * 16), Image.NEAREST))
        sh = Image.new("RGBA", (sum(i.width for i in ims) + 20, max(i.height for i in ims)), (30, 30, 34, 255))
        x = 0
        for i in ims:
            sh.paste(i, (x, 0))
            x += i.width + 20
        sh.save(a.sheet)


if __name__ == "__main__":
    main()
