import {useRef,useState} from 'react';
import {Minus,Plus,LocateFixed} from 'lucide-react';

const rooms=[['arrival','Arrival',95,235],['junction','Junction',275,235],['dispatch','Dispatch',470,235],['arena','Arena',670,235],['hearth','Counter',275,405],['treasury','Treasury',475,405],['archive','Archive',90,405],['lookout','Lookout',275,70],['reservoir','Reservoir',475,70],['gallery','Gallery',735,70],['return-shaft','Return lift',735,405]] as const;
const links=[['arrival','junction'],['junction','dispatch'],['dispatch','arena'],['junction','hearth'],['hearth','treasury'],['junction','archive'],['archive','treasury'],['junction','lookout'],['lookout','reservoir'],['reservoir','gallery'],['gallery','return-shaft'],['return-shaft','treasury']];
export function MapRecord({roomId,discovered}:{roomId:string;discovered:string[]}) {
 const [zoom,setZoom]=useState(1);const scroll=useRef<HTMLDivElement>(null);
 const focusCurrent=()=>{const room=rooms.find(r=>r[0]===roomId);if(room&&scroll.current)scroll.current.scrollTo({left:room[2]*zoom-scroll.current.clientWidth/2,top:room[3]*zoom-scroll.current.clientHeight/2,behavior:'instant'})};
 return <div className="v2-map-record"><div className="v2-map-tools"><span>{rooms.find(r=>r[0]===roomId)?.[1]||'World'}</span><button aria-label="Zoom map out" disabled={zoom<=.75} onClick={()=>setZoom(z=>Math.max(.75,z-.25))}><Minus size={17}/></button><output>{Math.round(zoom*100)}%</output><button aria-label="Zoom map in" disabled={zoom>=2} onClick={()=>setZoom(z=>Math.min(2,z+.25))}><Plus size={17}/></button><button aria-label="Locate current room" onClick={focusCurrent}><LocateFixed size={17}/></button></div>
 <div className="v2-map-scroll" ref={scroll} tabIndex={0} role="region" aria-label="World map; scroll to inspect routes"><svg width={900*zoom} height={490*zoom} viewBox="0 0 900 490" role="img" aria-label={`World layout. Current room: ${roomId}. Lines show connected rooms; this map does not travel.`}><defs><pattern id="map-grid" width="20" height="20" patternUnits="userSpaceOnUse"><path d="M20 0H0V20" fill="none" stroke="currentColor" opacity=".07"/></pattern></defs><rect width="900" height="490" fill="url(#map-grid)"/>{links.map(([a,b])=>{const p=rooms.find(r=>r[0]===a)!,q=rooms.find(r=>r[0]===b)!;return <path key={a+b} d={`M${p[2]} ${p[3]} H${(p[2]+q[2])/2} V${q[3]} H${q[2]}`} fill="none" stroke="currentColor" strokeWidth="2" strokeDasharray={a==='return-shaft'||b==='return-shaft'?'5 5':undefined} opacity=".5"/>})}{rooms.map(([id,title,x,y])=><g key={id} transform={`translate(${x} ${y})`} opacity={discovered.includes(id)||id===roomId?1:.48}><rect x="-46" y="-22" width="92" height="44" rx="1" fill={id===roomId?'#8e4337':'#d7c9a7'} stroke="currentColor" strokeWidth="2"/><text y="5" textAnchor="middle" fill={id===roomId?'#fff1cf':'currentColor'} fontSize="15">{title}</text>{id===roomId&&<path d="M-4 33L0 27L4 33L0 39Z" fill="#a64c3d"/>}</g>)}</svg></div>
 <p className="v2-map-legend"><span><i/>Current room</span><span>Faint rooms: not yet visited</span><span>Dashed line: return lift</span></p></div>;
}
