import fs from 'node:fs/promises';import assert from 'node:assert/strict';import {createRequire} from 'node:module';
const require=createRequire('D:/Dex/Projects/dex-place-world/site/package.json');const {chromium}=require(require.resolve('playwright',{paths:[require.resolve('@playwright/test')]}));
const out='D:/Dex/Automation/Proofs/dex-place/registry-20260913-root-release';await fs.mkdir(out,{recursive:true});
const browser=await chromium.launch({headless:true,executablePath:'C:/Users/sanic/AppData/Local/BraveSoftware/Brave-Browser/Application/brave.exe',args:['--mute-audio']});
const context=await browser.newContext({viewport:{width:1600,height:900}});const page=await context.newPage(),errors=[],failures=[],requests=[];
page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{requests.push(r.url());if(r.status()>=400)failures.push({url:r.url(),status:r.status()})});
await page.addInitScript(()=>{localStorage.clear();localStorage.setItem('dex.registry.preferences.v1',JSON.stringify({sound:false}))});
let result={};try{
 const response=await page.goto('http://127.0.0.1:5195/');assert.equal(response.status(),200);await page.getByRole('button',{name:'Enter',exact:true}).waitFor();await page.screenshot({path:out+'/packaged-entry.png'});
 await page.getByRole('button',{name:'Enter',exact:true}).click();await page.waitForTimeout(1700);const first=await page.evaluate(()=>__registry.snapshot());assert(first.active&&first.room==='arrival');await page.screenshot({path:out+'/packaged-arrival.png'});
 await page.keyboard.down('d');await page.waitForTimeout(550);await page.keyboard.down('Space');await page.waitForTimeout(120);await page.keyboard.up('Space');await page.waitForTimeout(70);await page.keyboard.press('Space');await page.waitForTimeout(170);await page.keyboard.up('d');const moved=await page.evaluate(()=>__registry.snapshot());assert(moved.player.x>first.player.x&&moved.player.doubleJumps===1);await page.waitForTimeout(1300);
 await page.keyboard.press('Escape');await page.getByRole('button',{name:'Settings',exact:true}).click();await page.getByRole('dialog',{name:'Settings',exact:true}).waitFor();await page.screenshot({path:out+'/packaged-settings.png'});await page.keyboard.press('Escape');await page.getByRole('dialog',{name:'Pause',exact:true}).waitFor();await page.keyboard.press('Escape');assert(await page.evaluate(()=>__registry.snapshot().active&&document.activeElement.classList.contains('registry-canvas')));
 await page.waitForTimeout(1800);const after=await page.evaluate(()=>__registry.snapshot());assert.equal(errors.length,0);assert.equal(failures.length,0);assert(!requests.some(url=>url.includes('/src/')||url.includes('@vite/client')));
 result={status:'pass',scope:'Independent root launch/input/panel check of standalone packaged build; no source-dev requests or asset substitution. Headless sound is muted; this is not audio listening proof.',url:'http://127.0.0.1:5195/',catalogue:after.resources.catalogue,checks:['HTTP200','real material entry','immediate controls','native movement and double jump','nested settings focus/close','no Vite/source requests','no failed HTTP responses','no JS exceptions'],first,after,errors,failures};
}catch(e){result={status:'fail',error:String(e.stack||e),errors,failures};console.error(String(e));process.exitCode=1;}finally{await context.close();await fs.writeFile(out+'/receipt.json',JSON.stringify(result,null,2));await browser.close();console.log(JSON.stringify({status:result.status,out,catalogue:result.catalogue}));}
